Implemented: stock schema design, action to fetch stock for multiple products and defined tranformation rule for stock response(#2v1pmpv)
hotwax/oms-api pull request #13
Opened 2022-09-23 09:41 UTC by ymaheshwari1

### Related Issues

Closes #

### Short Description and Why It's Useful

- Defined an action to call checkInventory api which fetches the stock for multiple product at once
- Added tranformation rule to return the response from oms package as per the stock schema design

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/oms-api/blob/main/CONTRIBUTING.md)

2023-01-10 12:25 UTC, adityasharma7 requested changes

2023-01-10 12:25 UTC, adityasharma7 commented on src/modules/stock/index.ts
> +async function fetchProductsStock(productIds: Array<string>, facilityId?: string): Promise<Array<Stock> | Response> {
As we are not fetching overall inventory in this method, we should rename based upon use case

2023-01-11 11:02 UTC, adityasharma7 requested changes

2023-01-11 11:02 UTC, adityasharma7 commented on src/modules/stock/index.ts
> +async function fetchProductsStockAsPerFacility(productIds: Array<string>, facilityId?: string): Promise<Array<Stock> | Response> {
```suggestion
async function fetchProductsStockAtFacility(productIds: Array<string>, facilityId?: string): Promise<Array<Stock> | Response> {
```

2023-01-11 11:15 UTC, ymaheshwari1 commented on src/modules/stock/index.ts
> +async function fetchProductsStockAsPerFacility(productIds: Array<string>, facilityId?: string): Promise<Array<Stock> | Response> {
Improved method name

2023-01-11 11:15 UTC, merged

2023-01-11 11:15 UTC, ymaheshwari1 commented on src/modules/stock/index.ts
> +    "viewSize": productIds.length,
Improved calculation of viewSize and added some comments