Implemented: code to define success response schema
hotwax/oms-api pull request #47
Opened 2023-01-09 09:16 UTC by ymaheshwari1

### Related Issues

Closes #38 

### Short Description and Why It's Useful

Added two different approaches for defining schema
1. ) Using Generics:

Defined an interface using generics, so as the same can be directly used for different type of success responses. Also added another property as object `count` that contains indexable types to contains different types of count like total (for total number of products), matches (in case when we are fetching resps as groups).

2.) By extending interface

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/oms-api/blob/main/CONTRIBUTING.md)

2023-01-09 10:22 UTC, adityasharma7 requested changes

2023-01-09 10:22 UTC, adityasharma7 commented on src/types/index.ts
> +interface SuccessResponse<Type> {
This pattern looks good

2023-01-09 11:00 UTC, ymaheshwari1 commented on src/types/index.ts
> +    [x: string]: number;
Added `total` and `groups` attributes at root of schema.

2023-01-09 11:00 UTC, ymaheshwari1 commented on src/types/index.ts
> +interface SuccessResponse<Type> {
Ok Sir

2023-01-10 12:15 UTC, adityasharma7 requested changes

2026-05-07 10:59 UTC, closed without merging