Implemented: API calls to get user preferred store and ecom stores in user module
hotwax/oms-api pull request #74
Opened 2023-10-09 11:29 UTC by sanskar345

### Related Issues

Related - https://github.com/hotwax/dxp-components/issues/193

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/oms-api/blob/main/CONTRIBUTING.md)

2023-10-09 12:38 UTC, k2maan requested changes

2023-10-09 12:38 UTC, k2maan commented on src/modules/user/index.ts
> +async function getEComStores (facilityId: string, token: any, baseURL: string): Promise<Response> {
Why are mentioning the returned type as `Promise<Response>`

2023-10-09 12:38 UTC, k2maan commented on src/modules/user/index.ts
> +    if (hasError(resp) || resp.data.docs.length === 0) {
This check might not be required `resp.data.docs.length === 0`

2023-10-09 12:38 UTC, k2maan commented on src/modules/user/index.ts
> +    return Promise.resolve(resp.data.userPrefValue ? resp.data.userPrefValue : '');
```suggestion
    return Promise.resolve(resp.data.userPrefValue);
```

2024-09-10 05:59 UTC, ymaheshwari1 commented
Closing as handled in https://github.com/hotwax/oms-api/pull/87

2024-09-10 05:59 UTC, closed without merging